[programs.localnet]
random_prize_game = "2u6cS6xYLNYrLeBxvwSUhBLVzEPNHety2UK8AvAXeybj"
[programs.devnet]
random_prize_game = "2u6cS6xYLNYrLeBxvwSUhBLVzEPNHety2UK8AvAXeybj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/wstar/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
